run:
	sass scss/mwenscss.scss css/mwen.css
	sass scss/_title.scss css/_title.css
	sass scss/_header.scss css/_header.css
	sass scss/_media.scss css/_media.css
	sass scss/_animation.scss css/_animation.css
